### ISSUE TITLE
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:

### ISSUE THREAD

**Issue by luminous33** [YuxiangZhang-BIT/IEEE_TIP_SDEnet#1]
I'm encountering a TypeError in our project and would like to inquire about it. The error message is as follows:

TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

The error occurs on line 23 of /data/test/IEEE_TIP_SDEnet/network/discriminator.py. It seems that the nn.Linear() function is causing the error due to receiving incorrect arguments when calling torch.empty().

We would appreciate any help or advice you could offer regarding this issue. Thank you very much:)

**Comment by luminous33** [comment]
Traceback (most recent call last):
  File "/data/test/IEEE_TIP_SDEnet/train.py", line 257, in <module>
    experiment()
  File "/data/test/IEEE_TIP_SDEnet/train.py", line 166, in experiment
    D_net = discriminator.Discriminator(inchannel=N_BANDS, outchannel=args.pro_dim, num_classes=num_classes, 
  File "/data/test/IEEE_TIP_SDEnet/network/discriminator.py", line 23, in __init__
    self.cls_head_src = nn.Linear(dim, num_classes)
  File "/usr/local/anaconda3/envs/hyper_image/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 86, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by fanleyuan** [comment]
修改discriminator.py中第23行为self.cls_head_src = nn.Linear(dim, int(num_classes))

**Comment by fanleyuan** [comment]
修改discriminator.py中第23行为self.cls_head_src = nn.Linear(dim, int(num_classes))
