### ISSUE TITLE
AttributeError: 'File' object has no attribute 'transpose'

### ISSUE THREAD

**Issue by xcxcever** [YuxiangZhang-BIT/IEEE_TIP_SDEnet#3]
我跑SDE和LDG都遇到数据读取不进来的问题
Traceback (most recent call last):
  File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\train.py", line 256, in <module>
    experiment()
  File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\train.py", line 114, in experiment
    img_src, gt_src, LABEL_VALUES_src, IGNORED_LABELS, RGB_BANDS, palette = get_dataset(args.source_name,
  File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\datasets.py", line 103, in get_dataset
    img = open_file(folder + 'Houston13.mat')['ori_data']
  File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\utils_HSI.py", line 45, in open_file
    return h5py.File(dataset).transpose(1, 2, 0)
AttributeError: 'File' object has no attribute 'transpose'

**Comment by YuxiangZhang-BIT** [comment]
我在datasets.py的get_dataset()和在utils_HSI.py的open_file()中做了修改。如有问题再联系我~

**Comment by YuxiangZhang-BIT** [comment]
> 我跑SDE和LDG都遇到数据读取不进来的问题 Traceback (most recent call last): File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\train.py", line 256, in experiment() File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\train.py", line 114, in experiment img_src, gt_src, LABEL_VALUES_src, IGNORED_LABELS, RGB_BANDS, palette = get_dataset(args.source_name, File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\datasets.py", line 103, in get_dataset img = open_file(folder + 'Houston13.mat')['ori_data'] File "D:\code\IEEE_TIP_SDEnet-main\IEEE_TIP_SDEnet-main\utils_HSI.py", line 45, in open_file return h5py.File(dataset).transpose(1, 2, 0) AttributeError: 'File' object has no attribute 'transpose'

我在datasets.py的get_dataset()和在utils_HSI.py的open_file()中做了修改。如有问题再联系我~

**Comment by xcxcever** [comment]
作者您好：
我这两天调试的时候遇到TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
